version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-single-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 개발용, 인증 비활성화
      - ES_JAVA_OPTS=-Xms1g -Xmx1g   # JVM 메모리 설정
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - es-net
    depends_on:
      - elasticsearch

volumes:
  es-data:

networks:
  es-net:
    driver: bridge
